# Generated by Django 3.2.6 on 2021-08-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('DebtorsID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome/Razão Social')),
                ('id_tax', models.CharField(max_length=20, verbose_name='CNPJ/CPF')),
                ('id_espaider', models.CharField(max_length=10, verbose_name='ID Espaider')),
                ('contabil', models.DecimalField(decimal_places=2, default='0', max_digits=15, verbose_name='Contábil')),
                ('risco', models.DecimalField(decimal_places=2, default='0', max_digits=15, verbose_name='Risco')),
                ('wallet_type', models.CharField(choices=[('MASSIFICADO PF', 'MASSIFICADO PF'), ('MASSIFICADO PJ', 'MASSIFICADO PJ'), ('AUTOS', 'AUTOS'), ('ALTO TICKET', 'ALTO TICKET')], default='MASSIFICADO PF', max_length=20)),
                ('phone_1', models.CharField(max_length=11, verbose_name='Telefone')),
                ('phone_2', models.CharField(max_length=11, verbose_name='Telefone')),
                ('phone_hot', models.CharField(max_length=11, verbose_name='Telefone Hot')),
                ('phone_whatsapp', models.CharField(max_length=11, verbose_name='Whatsapp')),
                ('status_negociacao', models.CharField(choices=[('NEGOCIAR', 'NEGOCIAR'), ('POTENCIAL', 'POTENCIAL'), ('PROPOSTA EM ANÁLISE', 'PROPOSTA EM ANÁLISE'), ('PROPOSTA APROVADA', 'PROPOSTA APROVADA'), ('PROPOSTA NEGADA', 'PROPOSTA NEGADA'), ('PROPOSTA EXPURGADA', 'PROPOSTA EXPURGADA'), ('PROPOSTA EXPURGA', 'PROPOSTA EXPURGADA'), ('ACORDO SEM ENTRADA', 'ACORDO SEM ENTRADA'), ('ACORDO PAGO', 'ACORDO PAGO'), ('FORMALIZADO', 'FORMALIZADO'), ('ACORDO EM DIA', 'ACORDO EM DIA'), ('ACORDO EXTERNO', 'ACORDO EXTERNO'), ('ACORDO QUITADO', 'ACORDO QUITADO'), ('DESINDICADO', 'DESINDICADO'), ('ACORDO ATIVO', 'ACORDO ATIVO'), ('NÃO ATUAR', 'NÃO ATUAR')], default='NEGOCIAR', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('cpc_status', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=20)),
                ('observacoes_status', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('user_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
