# Generated by Django 3.2.6 on 2021-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devedor', '0002_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='PhotoFileNAme',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
