# Generated by Django 3.2.5 on 2021-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devedor',
            name='id_espaider',
            field=models.CharField(max_length=10, verbose_name='ID Espaider'),
        ),
    ]
